-- ============================================================================
-- LICENCIAS OFFICE (ADQ-09) — buzones de grupo de Microsoft 365 (2026-09-29)
-- Fuente: pantalla «Licencias Office» del sistema PHP de PROMANT. Cada persona
-- dentro de un grupo es una licencia; paga PROMANT, usan las tres razones
-- sociales. Permisos: módulo `activos` (lectura nivel ≥ 1 por RLS y vista
-- invoker; escritura nivel ≥ 2 SOLO por RPC). Vive como bloque @@LICENCIAS@@ al
-- final de seguridad.sql (scripts/licencias-generar.mjs), NO en CANONICOS de
-- pg-local: los ensayos de fases anteriores lo recortan como a @@FACTOR@@.
-- (usa fn_nivel_modulo, fn_auditar, personas, vinculos, empresas). Idempotente.
-- Spec: docs/superpowers/specs/2026-09-29-licencias-office-design.md
-- ============================================================================

create table if not exists licencias_office (
  id        bigint generated by default as identity primary key,
  grupo     text not null unique check (grupo = upper(btrim(grupo)) and length(grupo) between 2 and 40),
  correo    text not null unique check (correo = lower(btrim(correo)) and correo ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  paga      text not null default 'promant' references empresas(id),
  estado    text not null default 'activa' check (estado in ('activa', 'suspendida', 'baja')),
  alta      date not null default current_date,
  creado_en timestamptz not null default now()
);
create table if not exists licencias_office_personas (
  id          bigint generated by default as identity primary key,
  licencia_id bigint not null references licencias_office(id) on delete cascade,
  dni         text references personas(dni),   -- null = por afiliar
  nombre      text not null,                   -- instantánea: fuente, o padrón al afiliar
  desde       date not null default current_date,
  hasta       date
);
create unique index if not exists uq_licencia_persona_abierta
  on licencias_office_personas (licencia_id, dni) where hasta is null and dni is not null;

-- Auditoría (fn_auditar es genérica: tabla + fila antes/después).
drop trigger if exists trg_auditar_licencias_office on licencias_office;
create trigger trg_auditar_licencias_office after insert or update or delete on licencias_office
  for each row execute function fn_auditar();
drop trigger if exists trg_auditar_licencias_office_personas on licencias_office_personas;
create trigger trg_auditar_licencias_office_personas after insert or update or delete on licencias_office_personas
  for each row execute function fn_auditar();

-- Vista del BackOffice: un grupo por fila con sus personas abiertas.
drop view if exists v_licencias_office;
create view v_licencias_office with (security_invoker = on) as
select l.id, l.grupo, l.correo, l.estado, l.paga, to_char(l.alta, 'YYYY-MM-DD') as alta,
       coalesce(jsonb_agg(jsonb_build_object('id', lp.id, 'dni', lp.dni, 'nombre', coalesce(p.nombre, lp.nombre),
                                             'empresa', ve.empresa_id, 'afiliado', lp.dni is not null)
                          order by coalesce(p.nombre, lp.nombre)) filter (where lp.id is not null), '[]'::jsonb) as personas,
       count(lp.id)::int as cantidad,
       (count(lp.id) filter (where lp.dni is null))::int as "porAfiliar"
from licencias_office l
left join licencias_office_personas lp on lp.licencia_id = l.id and lp.hasta is null
left join personas p on p.dni = lp.dni
left join lateral (select v.empresa_id from vinculos v where v.persona_dni = lp.dni and v.fecha_fin is null
                   order by v.fecha_inicio desc limit 1) ve on true
group by l.id
order by l.grupo;

-- RPC (definer, guarda propia sobre fn_nivel_modulo('activos') >= 2).
create or replace function guardar_licencia_office(p_id bigint, p_grupo text, p_correo text, p_estado text)
returns bigint language plpgsql security definer set search_path = public, interno, extensions as $$
declare v_id bigint;
        v_grupo text := upper(btrim(coalesce(p_grupo, '')));
        v_correo text := lower(btrim(coalesce(p_correo, '')));
        v_estado text := coalesce(nullif(btrim(p_estado), ''), 'activa');
begin
  if fn_nivel_modulo('activos') < 2 then raise exception 'Se necesita nivel de acción en Gestión de TI.' using errcode = '42501'; end if;
  if length(v_grupo) < 2 or length(v_grupo) > 40 then raise exception 'El grupo necesita entre 2 y 40 caracteres.'; end if;
  if v_correo !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Correo del buzón inválido.'; end if;
  if v_estado not in ('activa', 'suspendida', 'baja') then raise exception 'Estado inválido.'; end if;
  if exists (select 1 from licencias_office where (grupo = v_grupo or correo = v_correo) and id is distinct from p_id) then
    raise exception 'Ya existe un grupo con ese nombre o ese correo.';
  end if;
  if p_id is null then
    insert into licencias_office (grupo, correo, estado) values (v_grupo, v_correo, v_estado) returning id into v_id;
  else
    update licencias_office set grupo = v_grupo, correo = v_correo, estado = v_estado where id = p_id returning id into v_id;
    if v_id is null then raise exception 'El grupo no existe.'; end if;
  end if;
  return v_id;
end $$;

create or replace function afiliar_licencia_office(p_licencia bigint, p_dni text, p_nombre text default null, p_fila bigint default null)
returns bigint language plpgsql security definer set search_path = public, interno, extensions as $$
declare v_dni text := nullif(btrim(coalesce(p_dni, '')), ''); v_nombre text; v_id bigint;
begin
  if fn_nivel_modulo('activos') < 2 then raise exception 'Se necesita nivel de acción en Gestión de TI.' using errcode = '42501'; end if;
  if not exists (select 1 from licencias_office where id = p_licencia) then raise exception 'El grupo no existe.'; end if;
  if v_dni is not null then
    select nombre into v_nombre from personas where dni = v_dni;
    if v_nombre is null then raise exception 'El DNI % no está en el padrón.', v_dni; end if;
    if exists (select 1 from licencias_office_personas
               where licencia_id = p_licencia and dni = v_dni and hasta is null and id is distinct from p_fila) then
      raise exception 'Esa persona ya está afiliada a este grupo.';
    end if;
  else
    v_nombre := nullif(btrim(coalesce(p_nombre, '')), '');
    if v_nombre is null then raise exception 'Indica el DNI del padrón o el nombre de la persona.'; end if;
  end if;
  if p_fila is not null then
    update licencias_office_personas set dni = v_dni, nombre = v_nombre
     where id = p_fila and licencia_id = p_licencia and hasta is null returning id into v_id;
    if v_id is null then raise exception 'La fila por afiliar no existe o ya está cerrada.'; end if;
  else
    insert into licencias_office_personas (licencia_id, dni, nombre) values (p_licencia, v_dni, v_nombre) returning id into v_id;
  end if;
  return v_id;
end $$;

create or replace function desafiliar_licencia_office(p_fila bigint)
returns void language plpgsql security definer set search_path = public, interno, extensions as $$
begin
  if fn_nivel_modulo('activos') < 2 then raise exception 'Se necesita nivel de acción en Gestión de TI.' using errcode = '42501'; end if;
  update licencias_office_personas set hasta = current_date where id = p_fila and hasta is null;
  if not found then raise exception 'La afiliación no existe o ya está cerrada.'; end if;
end $$;

-- Permisos: tablas solo SELECT (la vista invoker las atraviesa por RLS); escritura solo por RPC.
revoke all on licencias_office, licencias_office_personas from public, anon, authenticated;
grant select on licencias_office, licencias_office_personas to authenticated;
revoke all on v_licencias_office from public, anon, authenticated;  -- default privileges de la plataforma dan todo
grant select on v_licencias_office to authenticated;
revoke all on function guardar_licencia_office(bigint, text, text, text), afiliar_licencia_office(bigint, text, text, bigint),
  desafiliar_licencia_office(bigint) from public, anon;
grant execute on function guardar_licencia_office(bigint, text, text, text), afiliar_licencia_office(bigint, text, text, bigint),
  desafiliar_licencia_office(bigint) to authenticated, service_role;
alter table licencias_office enable row level security;
alter table licencias_office_personas enable row level security;
drop policy if exists adm_lectura on licencias_office;
create policy adm_lectura on licencias_office for select to authenticated using ((select public.nivel_en('activos')) >= 1);
drop policy if exists adm_lectura on licencias_office_personas;
create policy adm_lectura on licencias_office_personas for select to authenticated using ((select public.nivel_en('activos')) >= 1);
