-- supabase/respaldos/2026-09-17-fase0-reversion.sql
-- REVERSIÓN COMPLETA de la fase 0 (migraciones/2026-09-17-fase0-contencion.sql).
-- Ensayada en Postgres local por scripts/ensayar-fase0.mjs: tras aplicarla, la foto
-- de permisos (ACL de funciones/tablas/vistas/secuencias, políticas, RLS y default
-- privileges) vuelve a ser IDÉNTICA a la anterior a la migración.
-- UNA transacción. Aplicar con: node scripts/aplicar-sql.mjs supabase/respaldos/2026-09-17-fase0-reversion.sql
begin;

-- Objetos creados por la fase 0
drop table if exists public.correo_envios;
drop policy if exists solo_admin on public.lineas;
-- portal_dni / portal_modo vuelven a SECURITY INVOKER sin search_path (así estaban)
alter function public.portal_dni() security invoker;
alter function public.portal_dni() reset search_path;
alter function public.portal_modo(p_dni text) security invoker;
alter function public.portal_modo(p_dni text) reset search_path;

-- Foto del paso 0 (2026-09-17T16:45Z): grants, políticas acceso_demo y estado RLS
-- Reversión de la fase 0 · foto de permisos tomada el 2026-09-17T16:45:17.781Z
-- Restituye EXACTAMENTE los grants a anon/authenticated y las políticas que existían.

-- Funciones
grant execute on function public."actualizar_ticket"(p_id bigint, p_estado text, p_atendido_por text, p_nota text, p_por text) to authenticated;
grant execute on function public."actualizar_usuario_admin"(p_id bigint, p_perfil text, p_correo text, p_celular text, p_estado text) to authenticated;
grant execute on function public."alta_trabajador"(p_dni text, p_nombre text, p_cargo text, p_sede text, p_empresa text, p_ingreso date, p_celular text, p_banco text, p_cuenta text, p_correo text, p_cci text, p_tipo_documento text) to authenticated;
grant execute on function public."alternar_ticket_subtipo"(p_id integer, p_activo boolean) to authenticated;
grant execute on function public."alternar_ticket_tipo"(p_id integer, p_activo boolean) to authenticated;
grant execute on function public."asignar_activo"(p_codigo text, p_dni text, p_condicion text, p_antivirus boolean, p_comentario text) to authenticated;
grant execute on function public."asignar_activo"(p_codigo text, p_dni text, p_condicion text) to authenticated;
grant execute on function public."asignar_rit_sede"(p_sede text, p_rit text) to authenticated;
grant execute on function public."crear_activo"(p_codigo text, p_categoria text, p_empresa text, p_tipo text, p_marca text, p_modelo text, p_serie text, p_imei text, p_valor numeric, p_compra date, p_observaciones text) to authenticated;
grant execute on function public."crear_rit"(p_nombre text, p_archivo text, p_hash text, p_vigente date) to authenticated;
grant execute on function public."crear_sede"(p_empresa text, p_nombre text, p_cliente text, p_direccion text, p_por text, p_rit text) to authenticated;
grant execute on function public."crear_solicitud_admin"(p_dni text, p_tipo text, p_datos jsonb, p_por text) to authenticated;
grant execute on function public."crear_solicitud_propia"(p_tipo text, p_datos jsonb) to authenticated;
grant execute on function public."crear_ticket_admin"(p_dni text, p_tipo integer, p_subtipo integer, p_comentario text, p_por text) to authenticated;
grant execute on function public."crear_usuario_admin"(p_dni text, p_perfil text, p_correo text, p_celular text, p_clave text, p_por text) to authenticated;
grant execute on function public."decidir_propuesta_perfil"(p_id bigint, p_decision text, p_por text) to authenticated;
grant execute on function public."desactivar_perfil"(p_id text) to authenticated;
grant execute on function public."devolver_activo"(p_codigo text, p_destino text, p_condicion text) to authenticated;
grant execute on function public."editar_activo"(p_codigo text, p_nuevo_codigo text, p_tipo text, p_marca text, p_modelo text, p_serie text, p_area text, p_asignado_sin_confirmar text, p_observaciones text, p_por text, p_ip text) to authenticated;
grant execute on function public."editar_trabajador"(p_dni text, p_nombre text, p_celular text, p_correo text, p_banco text, p_cuenta text, p_cci text, p_tipo_documento text) to authenticated;
grant execute on function public."eliminar_feriado"(p_fecha date, p_por text) to authenticated;
grant execute on function public."eliminar_perfil"(p_id text) to authenticated;
grant execute on function public."eliminar_sede"(p_sede text) to authenticated;
grant execute on function public."eliminar_solicitud_aviso"(p_id bigint) to authenticated;
grant execute on function public."eliminar_ticket_aviso"(p_correo text) to authenticated;
grant execute on function public."eliminar_trabajador"(p_dni text) to authenticated;
grant execute on function public."eliminar_usuario_admin"(p_id bigint) to authenticated;
grant execute on function public."emitir_memorandum"(p_dni text, p_tipo_sancion text, p_falta_id bigint, p_motivo text, p_suspension_dias integer, p_por text) to authenticated;
grant execute on function public."es_admin_activo"() to authenticated;
grant execute on function public."fijar_correo_persona"(p_dni text, p_correo text) to authenticated;
grant execute on function public."fijar_hora_entrada"(p_dni text, p_hora time without time zone, p_desde date, p_por text) to authenticated;
grant execute on function public."fn_auditar"() to authenticated;
grant execute on function public."fn_bloquear_cambios"() to authenticated;
grant execute on function public."fn_es_prefijo_truncado"(p_nuevo text, p_actual text) to authenticated;
grant execute on function public."fn_hora_entrada"(p_dni text, p_fecha date) to authenticated;
grant execute on function public."fn_min_hhmm"(t text) to authenticated;
grant execute on function public."fn_movimientos_solo_insertar"() to authenticated;
grant execute on function public."fn_nivel_memorandums"() to authenticated;
grant execute on function public."fn_nivel_modulo"(p_modulo text) to authenticated;
grant execute on function public."fn_perfil_nombre_unico"() to authenticated;
grant execute on function public."fn_perfil_para_cargo"(p_cargo text) to authenticated;
grant execute on function public."fn_persona_llamador"() to authenticated;
grant execute on function public."fn_proteger_ultimo_superadmin"() to authenticated;
grant execute on function public."fn_recalcular_control"(p_documento text, p_desde date, p_hasta date, p_motivo text) to authenticated;
grant execute on function public."fn_recalcular_mes_feriado"(p_fecha date, p_motivo text) to authenticated;
grant execute on function public."fn_registro_solo_desvincular"() to authenticated;
grant execute on function public."fn_resolver_banco"(p_texto text) to authenticated;
grant execute on function public."fn_sede_para_importacion"(p_empresa text, p_sede text, p_cliente text) to authenticated;
grant execute on function public."fn_solicitud_eventos_inmutables"() to authenticated;
grant execute on function public."fn_solicitud_insertar"(p_dni text, p_tipo text, p_datos jsonb, p_por text) to authenticated;
grant execute on function public."fn_solicitud_numero"(p_tipo text, p_empresa text) to authenticated;
grant execute on function public."fn_solicitud_recalcula_asistencia"() to authenticated;
grant execute on function public."fn_solicitud_validar"(p_tipo text, p_datos jsonb) to authenticated;
grant execute on function public."fn_solo_empresa_activa"() to authenticated;
grant execute on function public."fn_sumar_dias"(p_desde date, p_dias integer, p_habiles boolean) to authenticated;
grant execute on function public."fn_superadmin_sin_matriz"() to authenticated;
grant execute on function public."fn_ticket_insertar"(p_dni text, p_tipo integer, p_subtipo integer, p_comentario text) to authenticated;
grant execute on function public."fn_ticket_numero"() to authenticated;
grant execute on function public."fn_validar_documento"(p_tipo text, p_numero text) to authenticated;
grant execute on function public."fn_valor_importado"(p_nuevo text, p_actual text) to authenticated;
grant execute on function public."fn_ver_cuenta_bancaria"(p_dni text) to authenticated;
grant execute on function public."guardar_cargo_perfil"(p_cargo text, p_destino text, p_perfil text, p_por text) to authenticated;
grant execute on function public."guardar_clave_equipo"(p_codigo text, p_clave text, p_por text) to authenticated;
grant execute on function public."guardar_feriado"(p_fecha date, p_nombre text, p_por text) to authenticated;
grant execute on function public."guardar_perfil"(p_id text, p_nombre text, p_descripcion text, p_superadmin boolean, p_ver_remuneracion boolean, p_ver_documentos boolean, p_exportar boolean, p_matriz jsonb, p_empresas text[], p_por text, p_ver_bancarios boolean) to authenticated;
grant execute on function public."guardar_politica"(p_backoffice_horas integer, p_portal_dias integer, p_multisesion_backoffice boolean, p_multisesion_portal boolean, p_intentos integer, p_bloqueo_min integer, p_recuperacion text, p_clave_min_portal integer, p_clave_min_backoffice integer, p_provisional_dias integer, p_por text) to authenticated;
grant execute on function public."guardar_solicitud_aviso"(p_tipo text, p_correo text, p_copia boolean, p_activo boolean) to authenticated;
grant execute on function public."guardar_ticket_aviso"(p_correo text, p_activo boolean) to authenticated;
grant execute on function public."guardar_ticket_subtipo"(p_id integer, p_tipo integer, p_nombre text) to authenticated;
grant execute on function public."guardar_ticket_tipo"(p_id integer, p_nombre text) to authenticated;
grant execute on function public."importar_activos"(p_empresa text, p_activos jsonb, p_razon_social text, p_archivo text, p_por text) to authenticated;
grant execute on function public."importar_asistencia"(p_empresa text, p_registros jsonb, p_archivo text, p_resumen jsonb, p_por text) to authenticated;
grant execute on function public."importar_control"(p_registros jsonb, p_trabajadores jsonb, p_archivo text, p_por text) to authenticated;
grant execute on function public."importar_padron"(p_filas jsonb, p_por text, p_ceses jsonb) to authenticated;
grant execute on function public."importar_planilla"(p_empresa text, p_filas jsonb, p_por text) to authenticated;
grant execute on function public."importar_planilla_unificada"(p_filas jsonb, p_periodo text, p_por text, p_ceses jsonb) to authenticated;
grant execute on function public."marcar_clave_cambiada"(p_correo text) to authenticated;
grant execute on function public."mi_sesion_backoffice"() to authenticated;
grant execute on function public."notificar_memorandum"(p_id text) to authenticated;
grant execute on function public."portal_actualizar_datos"(p_celular text, p_direccion text) to authenticated;
grant execute on function public."portal_confirmar_lectura"(p_comunicado_id bigint, p_dispositivo text) to authenticated;
grant execute on function public."portal_confirmar_recepcion"(p_documento_id bigint, p_dispositivo text) to authenticated;
grant execute on function public."portal_crear_solicitud"(p_tipo text, p_datos jsonb) to authenticated;
grant execute on function public."portal_crear_ticket"(p_tipo integer, p_subtipo integer, p_comentario text) to authenticated;
grant execute on function public."portal_dni"() to authenticated;
grant execute on function public."portal_marcar_visto"(p_comunicado_id bigint) to authenticated;
grant execute on function public."portal_mi_sesion"() to authenticated;
grant execute on function public."portal_modo"(p_dni text) to authenticated;
grant execute on function public."portal_primer_ingreso"(p_celular text, p_sin_celular boolean, p_politica_version integer, p_correo text) to authenticated;
grant execute on function public."portal_registrar_ingreso"(p_dni text, p_resultado text, p_dispositivo text) to anon;
grant execute on function public."portal_registrar_ingreso"(p_dni text, p_resultado text, p_dispositivo text) to authenticated;
grant execute on function public."portal_registrar_sesion"(p_marker text) to authenticated;
grant execute on function public."portal_solicitar_cambio_cuenta"(p_motivo text) to authenticated;
grant execute on function public."portal_verificar_bloqueo"(p_dni text) to anon;
grant execute on function public."portal_verificar_bloqueo"(p_dni text) to authenticated;
grant execute on function public."previsualizar_asistencia"(p_empresa text, p_registros jsonb, p_archivo text, p_resumen jsonb) to authenticated;
grant execute on function public."previsualizar_control"(p_registros jsonb, p_trabajadores jsonb, p_archivo text) to authenticated;
grant execute on function public."previsualizar_importacion"(p_empresa text, p_filas jsonb) to authenticated;
grant execute on function public."previsualizar_importacion_activos"(p_empresa text, p_activos jsonb, p_razon_social text, p_archivo text) to authenticated;
grant execute on function public."previsualizar_padron"(p_filas jsonb, p_ceses jsonb) to authenticated;
grant execute on function public."previsualizar_planilla_unificada"(p_filas jsonb, p_periodo text, p_ceses jsonb) to authenticated;
grant execute on function public."publicar_comunicado"(p_titulo text, p_cuerpo text, p_vence date, p_exige boolean, p_segmento text, p_alcance integer, p_empresa text, p_sede text) to authenticated;
grant execute on function public."publicar_lote"(p_empresa text, p_tipo text, p_periodo text, p_por text) to authenticated;
grant execute on function public."publicar_lote_pdf"(p_empresa text, p_tipo text, p_periodo text, p_por text, p_boletas jsonb) to authenticated;
grant execute on function public."publicar_rit"(p_archivo_url text, p_hash text, p_titulo text) to authenticated;
grant execute on function public."puede"(p_usuario bigint, p_modulo text, p_nivel integer, p_empresa text, p_sede text) to authenticated;
grant execute on function public."reactivar_usuario_admin"(p_id bigint) to authenticated;
grant execute on function public."reenviar_clave"(p_id bigint, p_clave text) to authenticated;
grant execute on function public."reenviar_solicitud"(p_id bigint, p_datos jsonb, p_por text) to authenticated;
grant execute on function public."registrar_acuse_asistido"(p_dni text, p_lote text, p_motivo text, p_entrega timestamp with time zone, p_adjunto text, p_dispositivo text) to authenticated;
grant execute on function public."registrar_epp"(p_dni text, p_items text, p_entrega date, p_reposicion date) to authenticated;
grant execute on function public."registrar_ingreso"(p_correo text, p_resultado text, p_dispositivo text) to anon;
grant execute on function public."registrar_ingreso"(p_correo text, p_resultado text, p_dispositivo text) to authenticated;
grant execute on function public."registrar_sesion_backoffice"(p_marker text) to authenticated;
grant execute on function public."resolver_memorandum"(p_id text, p_decision text) to authenticated;
grant execute on function public."resolver_solicitud"(p_id bigint, p_decision text, p_comentario text, p_por text) to authenticated;
grant execute on function public."suspender_usuario_admin"(p_id bigint) to authenticated;
grant execute on function public."ver_clave_equipo"(p_codigo text, p_por text) to authenticated;
grant execute on function public."verificar_bloqueo"(p_correo text) to anon;
grant execute on function public."verificar_bloqueo"(p_correo text) to authenticated;

-- Tablas y vistas
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."activos" to authenticated;
grant INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE on public."acuses" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."asignaciones" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."asistencia_config" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."asistencia_lotes" to authenticated;
grant INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE on public."auditoria" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."bancos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."cargo_perfiles" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."cargos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."centros_costo" to authenticated;
grant INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE on public."comunicado_lecturas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."comunicados" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."contratos" to authenticated;
grant REFERENCES,TRIGGER,TRUNCATE on public."correo_tokens" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."cuentas_portal" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."declaraciones" to authenticated;
grant INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE on public."descargos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."documentos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."empresas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."epp_entregas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."feriados" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."lineas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."lotes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."marcaciones" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."memorandums" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."perfil_empresas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."perfil_permisos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."perfiles" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."personas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."plantillas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."politica_acceso" to authenticated;
grant INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE on public."registro_accesos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."rit_faltas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."sedes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."solicitudes_cambio_cuenta" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."tardanzas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."tipos_sancion" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."usuarios_admin" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."vinculos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_actividad_persona" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_activos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_acuses" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_asistencia_lotes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_asistencia_mensual" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_cargo_perfiles" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_comunicado_pendientes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_comunicados" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_contratos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_declaraciones_vigentes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_epp_entregas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_feriados" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_lotes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_marcaciones" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_memorandums" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_mi_acceso" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_mis_solicitudes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_movimientos_persona" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_perfil_propuestas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_perfil_versiones" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_perfiles" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_personal" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_politica_acceso" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_boletas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_comunicados" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_datos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_mes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_pendientes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_perfil" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_rit" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_solicitudes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_portal_tickets" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_registro_accesos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_rit_faltas" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_rits" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_sedes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_solicitud_avisos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_solicitud_eventos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_solicitud_tipos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_solicitudes" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_ticket_avisos" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_ticket_catalogo" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_ticket_config" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_tickets" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_tipos_sancion" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_usuarios_admin" to authenticated;
grant DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on public."v_vinculos_persona" to authenticated;

-- Secuencias
grant usage, select on sequence public."acuses_id_seq" to authenticated;
grant usage, select on sequence public."asignaciones_id_seq" to authenticated;
grant usage, select on sequence public."asistencia_lotes_id_seq" to authenticated;
grant usage, select on sequence public."auditoria_id_seq" to authenticated;
grant usage, select on sequence public."comunicados_id_seq" to authenticated;
grant usage, select on sequence public."consentimientos_id_seq" to authenticated;
grant usage, select on sequence public."contratos_id_seq" to authenticated;
grant usage, select on sequence public."documentos_id_seq" to authenticated;
grant usage, select on sequence public."epp_entregas_id_seq" to authenticated;
grant usage, select on sequence public."movimientos_id_seq" to authenticated;
grant usage, select on sequence public."notificaciones_documento_id_seq" to authenticated;
grant usage, select on sequence public."perfil_propuestas_id_seq" to authenticated;
grant usage, select on sequence public."plantillas_id_seq" to authenticated;
grant usage, select on sequence public."registro_accesos_id_seq" to authenticated;
grant usage, select on sequence public."rit_faltas_id_seq" to authenticated;
grant usage, select on sequence public."seq_sede_codigo" to authenticated;
grant usage, select on sequence public."seq_ticket_numero" to authenticated;
grant usage, select on sequence public."seq_usuario_codigo" to authenticated;
grant usage, select on sequence public."solicitud_avisos_id_seq" to authenticated;
grant usage, select on sequence public."solicitud_eventos_id_seq" to authenticated;
grant usage, select on sequence public."solicitudes_cambio_cuenta_id_seq" to authenticated;
grant usage, select on sequence public."solicitudes_id_seq" to authenticated;
grant usage, select on sequence public."ticket_subtipos_id_seq" to authenticated;
grant usage, select on sequence public."ticket_tipos_id_seq" to authenticated;
grant usage, select on sequence public."tickets_id_seq" to authenticated;
grant usage, select on sequence public."usuarios_admin_id_seq" to authenticated;
grant usage, select on sequence public."vinculos_id_seq" to authenticated;

-- Políticas
drop policy if exists "acceso_demo" on public."activos";
create policy "acceso_demo" on public."activos" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."acuses";
create policy "acceso_demo" on public."acuses" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."asignaciones";
create policy "acceso_demo" on public."asignaciones" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."asistencia_config";
create policy "acceso_demo" on public."asistencia_config" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."asistencia_lotes";
create policy "acceso_demo" on public."asistencia_lotes" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."auditoria";
create policy "acceso_demo" on public."auditoria" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."bancos";
create policy "acceso_demo" on public."bancos" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."cargos";
create policy "acceso_demo" on public."cargos" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."comunicado_lecturas";
create policy "acceso_demo" on public."comunicado_lecturas" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."comunicados";
create policy "acceso_demo" on public."comunicados" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."contratos";
create policy "acceso_demo" on public."contratos" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."cuentas_portal";
create policy "acceso_demo" on public."cuentas_portal" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."declaraciones";
create policy "acceso_demo" on public."declaraciones" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."descargos";
create policy "acceso_demo" on public."descargos" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "documentos_admin" on public."documentos";
create policy "documentos_admin" on public."documentos" as permissive for ALL to authenticated using (es_admin_activo()) with check (es_admin_activo());
drop policy if exists "acceso_demo" on public."empresas";
create policy "acceso_demo" on public."empresas" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."epp_entregas";
create policy "acceso_demo" on public."epp_entregas" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."lineas";
create policy "acceso_demo" on public."lineas" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."lotes";
create policy "acceso_demo" on public."lotes" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."marcaciones";
create policy "acceso_demo" on public."marcaciones" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."memorandums";
create policy "acceso_demo" on public."memorandums" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."perfil_permisos";
create policy "acceso_demo" on public."perfil_permisos" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."perfiles";
create policy "acceso_demo" on public."perfiles" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."personas";
create policy "acceso_demo" on public."personas" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."plantillas";
create policy "acceso_demo" on public."plantillas" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."politica_acceso";
create policy "acceso_demo" on public."politica_acceso" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."registro_accesos";
create policy "acceso_demo" on public."registro_accesos" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."sedes";
create policy "acceso_demo" on public."sedes" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."solicitudes_cambio_cuenta";
create policy "acceso_demo" on public."solicitudes_cambio_cuenta" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."tardanzas";
create policy "acceso_demo" on public."tardanzas" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."usuarios_admin";
create policy "acceso_demo" on public."usuarios_admin" as permissive for ALL to authenticated using (true) with check (true);
drop policy if exists "acceso_demo" on public."vinculos";
create policy "acceso_demo" on public."vinculos" as permissive for ALL to authenticated using (true) with check (true);

-- RLS
alter table public."activos" enable row level security;
alter table public."acuses" enable row level security;
alter table public."asignaciones" enable row level security;
alter table public."asistencia_config" enable row level security;
alter table public."asistencia_lotes" enable row level security;
alter table public."auditoria" enable row level security;
alter table public."bancos" enable row level security;
alter table public."cargo_perfiles" disable row level security;
alter table public."cargos" enable row level security;
alter table public."centros_costo" disable row level security;
alter table public."comunicado_lecturas" enable row level security;
alter table public."comunicados" enable row level security;
alter table public."consentimientos" disable row level security;
alter table public."contratos" enable row level security;
alter table public."correo_tokens" disable row level security;
alter table public."cuentas_portal" enable row level security;
alter table public."declaraciones" enable row level security;
alter table public."descargos" enable row level security;
alter table public."documentos" enable row level security;
alter table public."empresas" enable row level security;
alter table public."epp_entregas" enable row level security;
alter table public."feriados" disable row level security;
alter table public."horarios_entrada" disable row level security;
alter table public."lineas" enable row level security;
alter table public."lotes" enable row level security;
alter table public."marcaciones" enable row level security;
alter table public."memorandums" enable row level security;
alter table public."movimientos" disable row level security;
alter table public."notificaciones_documento" disable row level security;
alter table public."perfil_empresas" disable row level security;
alter table public."perfil_permisos" enable row level security;
alter table public."perfil_propuestas" disable row level security;
alter table public."perfiles" enable row level security;
alter table public."personas" enable row level security;
alter table public."plantillas" enable row level security;
alter table public."politica_acceso" enable row level security;
alter table public."registro_accesos" enable row level security;
alter table public."rit_faltas" disable row level security;
alter table public."rits" disable row level security;
alter table public."sedes" enable row level security;
alter table public."solicitud_avisos" disable row level security;
alter table public."solicitud_correlativos" disable row level security;
alter table public."solicitud_eventos" disable row level security;
alter table public."solicitud_tipos" disable row level security;
alter table public."solicitudes" disable row level security;
alter table public."solicitudes_cambio_cuenta" enable row level security;
alter table public."tardanzas" enable row level security;
alter table public."ticket_avisos" disable row level security;
alter table public."ticket_subtipos" disable row level security;
alter table public."ticket_tipos" disable row level security;
alter table public."tickets" disable row level security;
alter table public."tipos_sancion" disable row level security;
alter table public."usuarios_admin" enable row level security;
alter table public."vinculos" enable row level security;

commit;
